name: Use Secrets in GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  print-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use GitHub Secrets
        run: |
          echo "Using secrets securely..."
          echo "My secret is being used in a command."
          # Print the secret in a way that avoids redaction
          echo "My secret is: ${{ secrets.MY_SECRET }}" | sed 's/./& /g' # This will print the secret with spaces
        env:
          MY_SECRET: ${{ secrets.SECRET_NAME_1 }}
