name: CI and CD Workflow

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run CI Tasks
        run: |
          echo "Running CI tasks..."
          # Add your CI tasks here (e.g., tests, builds)
          echo "CI job completed."

  wait-for-approval:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Wait for CEO approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: reaserch-linearloop

  cd:
    needs: wait-for-approval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy Application
        run: |
          echo "Running CD tasks..."
          echo "Deployment initiated by the CEO"
          # Add your deployment steps here
        env:
          MY_SECRET: ${{ secrets.SECRET_NAME_1 }}
          SECRET: ${{ secrets.SECRET }}
          MY_SECRET_2: ${{ secrets.MY_SECRET_2 }}
          MY_SECRET_1: ${{ secrets.MY_SECRET_1 }}
